### ISSUE TITLE
[PkgEval] Lumberjack may have a testing issue on Julia 0.3 (2014-08-23)

### ISSUE THREAD

**Issue by IainNZ** [forio/Lumberjack.jl#12]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.3) and the nightly build of the unstable version (0.4). The results of this script are used to generate a [package listing](http://pkg.julialang.org/) enhanced with testing results.

#### On Julia 0.3
* On **2014-08-22** the testing status was `Tests pass.`
* On **2014-08-23** the testing status changed to `Tests fail, but package loads.`

`Tests pass.` means that PackageEvaluator found the tests for your package, executed them, and they all passed.

`Tests fail, but package loads.` means that PackageEvaluator found the tests for your package, executed them, and they didn't pass. However, trying to load your package with `using` worked.

*This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added.*

*Test log*:
```
>>> 'Pkg.add("Lumberjack")' log
INFO: Installing Datetime v0.1.6
INFO: Installing Lumberjack v0.0.3
INFO: Installing UUID v0.0.2
INFO: Building Datetime
INFO: Package database updated

>>> 'using Lumberjack' log
Julia Version 0.3.0-rc4+4
Commit bab9636 (2014-08-20 18:47 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

>>> test log
ERROR: test failed: log_lines[1] == "$(Base.text_colors[:cyan])DEBUG: some-msg\n"
 in error at error.jl:21
 in default_handler at test.jl:19
 in do_test at test.jl:39
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in anonymous at no file:20
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
 in _start_3B_1718 at /home/idunning/julia03/usr/bin/../lib/julia/sys.so
while loading /home/idunning/pkgtest/.julia/v0.3/Lumberjack/test/test-lumberjack-opts.jl, in expression starting on line 29
while loading /home/idunning/pkgtest/.julia/v0.3/Lumberjack/test/runtests.jl, in expression starting on line 16


>>> end of log
```

**Comment by WestleyArgentum** [comment]
I believe this has been resolved, everything checks out on 0.3 and 0.4 right now
