### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by dmiljkovic** [forio/Lumberjack.jl#15]
Are you planning to add log rotation functionality.

Thanks,

Dejan

**Comment by WestleyArgentum** [comment]
Hey, I see you posted in #13 as well. I think that would be a great addition, but at the moment I don't have time to put towards it. Pull requests would of course be welcome though!

Alternatively, many systems already have things like "logrotate" on them. You may be able to drop in a config file for one of those and let them handle the details of rotating, compressing, etc.

**Comment by WestleyArgentum** [comment]
Fixed in #21 by @tmlbl, woo
