### ISSUE TITLE
Tag a release now that julia 0.4 is almost released

### ISSUE THREAD

**Issue by samtkaplan** [forio/Lumberjack.jl#27]
Hi,

Thanks for merging #26!

Would it be approprieate to make a release.  After #26, Lumberjack is working well for me on Julia 0.4.  But, I have to do:
```julia
Pkg.add("Lumberjack")
Pkg.checkout("Lumberjack")
```
Rather than just:
```julia
Pkg.add("Lumberjack")
```

Thanks!

Sam

**Comment by WestleyArgentum** [comment]
Hey! Sorry about that, I'd been meaning to tag for days, but it's done now: https://github.com/JuliaLang/METADATA.jl/pull/3713

**Comment by samtkaplan** [comment]
Awesome.   Thanks!
